#!/bin/bash

if [[ -z $1 || -z $2 ]]; then
	echo "Usage: deletelvms vg_name lvm_name"
	exit 1
else
	vg_name=$1
	lvm_name=$2

	lvm_to_remove=$(sudo lvm lvs -o lv_name $vg_name|grep $lvm_name)
	if [[ $? != 0 ]]; then
		echo "Error"
		exit 1
	fi

	echo This is going to delete the following:
	for k in $lvm_to_remove; do
		echo $k
	done
	echo "(y):yes (n):no"
	read yes_or_no
	if [[ $yes_or_no == 'y' ]]; then
		for i in $lvm_to_remove; do
			echo "deleting: "$vg_name'/'$i
			sudo lvm lvremove $vg_name'/'$i
			if [[ $? != 0 ]]; then
				echo "Failed to remove lvm. Check spelling"
				exit 1
			fi
		done
	else
		echo "Wrong usage or Cancelled by user"
	fi
fi
